tunnel: resumemcp
credentials-file: /workspaces/resume-mcp-server/.cloudflared/599718c3-ca5e-4347-8b65-2f80c1ef91cf.json

ingress:
  - hostname: resumedev.0x1f0c.dev
    service: http://localhost:8000

  - service: http_status:404
