version: "3.9"

services:
  devcontainer:
    build:
      context: .devcontainer/
      dockerfile: Dockerfile.base
    volumes:
      - .:/workspace

    depends_on:
      - redis
      - latex_compile_api
    command: ./cloudflared tunnel  --config ./.cloudflared/config.yml run

  redis:
    image: redis:7

  latex_compile_api:
    build:
      context: ./services/latex_compile_api
    ports:
      - "8080:8080"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
      - latex_compile_worker
    command: uvicorn app:app --host 0.0.0.0 --port 8080

  latex_compile_worker:
    build:
      context: ./services/latex_compile_api
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
    command: celery -A celery_app worker --loglevel=info --uid=nobody




